import * as React from "react";
import * as P from "@phosphor-icons/react";

export type IconWeight = P.IconWeight;
export type IconProps = P.IconProps;
export { IconContext } from "@phosphor-icons/react";

/**
 * Adapter wrapper that maps Lucide icon props to Phosphor Icons
 * Defaults to 'bold' weight for crisp, non-slop typography & iconography
 */
function createIcon(Component: P.Icon, defaultWeight: P.IconWeight = "bold") {
  const IconWrapper = React.forwardRef<SVGSVGElement, any>((props, ref) => {
    const { strokeWidth, weight = defaultWeight, className, ...rest } = props;
    return <Component ref={ref} weight={weight} className={className} {...rest} />;
  });
  IconWrapper.displayName = Component.displayName || "PhosphorIcon";
  return IconWrapper;
}

// 140 Mapped Lucide -> Phosphor Icons
export const Activity = createIcon(P.Pulse);
export const AlertCircle = createIcon(P.WarningCircle);
export const AlertOctagon = createIcon(P.WarningOctagon);
export const AlertTriangle = createIcon(P.Warning);
export const Archive = createIcon(P.Archive);
export const ArrowLeft = createIcon(P.ArrowLeft);
export const ArrowLeftRight = createIcon(P.ArrowsLeftRight);
export const ArrowRight = createIcon(P.ArrowRight);
export const Atom = createIcon(P.Atom);
export const Award = createIcon(P.Medal);
export const BarChart = createIcon(P.ChartBar);
export const BarChart2 = createIcon(P.ChartBar);
export const BarChart3 = createIcon(P.ChartBarHorizontal);
export const Bell = createIcon(P.Bell);
export const BookOpen = createIcon(P.BookOpen);
export const Bookmark = createIcon(P.BookmarkSimple);
export const Bot = createIcon(P.Robot);
export const BrainCircuit = createIcon(P.Brain);
export const Building = createIcon(P.Buildings);
export const Building2 = createIcon(P.BuildingApartment);
export const Calendar = createIcon(P.Calendar);
export const CalendarDays = createIcon(P.CalendarBlank);
export const Camera = createIcon(P.Camera);
export const Check = createIcon(P.Check);
export const CheckCircle = createIcon(P.CheckCircle);
export const CheckCircle2 = createIcon(P.CheckCircle);
export const CheckSquare = createIcon(P.CheckSquare);
export const ChevronDown = createIcon(P.CaretDown);
export const ChevronLeft = createIcon(P.CaretLeft);
export const ChevronRight = createIcon(P.CaretRight);
export const ChevronUp = createIcon(P.CaretUp);
export const ChevronsLeft = createIcon(P.CaretDoubleLeft);
export const ChevronsRight = createIcon(P.CaretDoubleRight);
export const ClipboardCheck = createIcon(P.ClipboardText);
export const ClipboardList = createIcon(P.Clipboard);
export const ClipboardPaste = createIcon(P.ClipboardText);
export const Clock = createIcon(P.Clock);
export const Cloud = createIcon(P.Cloud);
export const CloudOff = createIcon(P.CloudSlash);
export const Compass = createIcon(P.Compass);
export const Copy = createIcon(P.Copy);
export const Cpu = createIcon(P.Cpu);
export const Database = createIcon(P.Database);
export const Download = createIcon(P.DownloadSimple);
export const Edit = createIcon(P.PencilSimple);
export const Edit2 = createIcon(P.Pencil);
export const ExternalLink = createIcon(P.ArrowSquareOut);
export const Eye = createIcon(P.Eye);
export const EyeOff = createIcon(P.EyeSlash);
export const FileBox = createIcon(P.Package);
export const FileCheck = createIcon(P.FileText);
export const FileJson = createIcon(P.FileCode);
export const FileSpreadsheet = createIcon(P.FileXls);
export const FileText = createIcon(P.FileText);
export const Filter = createIcon(P.Funnel);
export const Flag = createIcon(P.Flag);
export const FolderOpen = createIcon(P.FolderOpen);
export const Forward = createIcon(P.ArrowFatRight);
export const Globe = createIcon(P.Globe);
export const GraduationCap = createIcon(P.GraduationCap);
export const GripVertical = createIcon(P.DotsSixVertical);
export const Hash = createIcon(P.Hash);
export const HelpCircle = createIcon(P.Question);
export const Home = createIcon(P.House);
export const Image = createIcon(P.Image);
export const Info = createIcon(P.Info);
export const Key = createIcon(P.Key);
export const KeyRound = createIcon(P.Keyhole);
export const Landmark = createIcon(P.Bank);
export const Laptop = createIcon(P.Laptop);
export const Layers = createIcon(P.Stack);
export const LayoutDashboard = createIcon(P.SquaresFour);
export const LayoutGrid = createIcon(P.GridFour);
export const LayoutTemplate = createIcon(P.Layout);
export const Library = createIcon(P.Books);
export const Lightbulb = createIcon(P.Lightbulb);
export const Loader2 = createIcon(P.CircleNotch);
export const Lock = createIcon(P.Lock);
export const LogOut = createIcon(P.SignOut);
export const Mail = createIcon(P.Envelope);
export const MapPin = createIcon(P.MapPin);
export const Maximize2 = createIcon(P.ArrowsOut);
export const Menu = createIcon(P.List);
export const MessageCircle = createIcon(P.ChatCircle);
export const Monitor = createIcon(P.Monitor);
export const Moon = createIcon(P.Moon);
export const MoreHorizontal = createIcon(P.DotsThree);
export const MoreVertical = createIcon(P.DotsThreeVertical);
export const Palette = createIcon(P.Palette);
export const Pencil = createIcon(P.Pencil);
export const Percent = createIcon(P.Percent);
export const Phone = createIcon(P.Phone);
export const PieChart = createIcon(P.ChartPieSlice);
export const Plus = createIcon(P.Plus);
export const Power = createIcon(P.Power);
export const PowerOff = createIcon(P.Power);
export const Printer = createIcon(P.Printer);
export const RefreshCcw = createIcon(P.ArrowCounterClockwise);
export const RefreshCw = createIcon(P.ArrowsClockwise);
export const RotateCcw = createIcon(P.ArrowCounterClockwise);
export const RotateCw = createIcon(P.ArrowClockwise);
export const Save = createIcon(P.FloppyDisk);
export const School = createIcon(P.GraduationCap);
export const Search = createIcon(P.MagnifyingGlass);
export const Send = createIcon(P.PaperPlaneRight);
export const Server = createIcon(P.HardDrives);
export const Settings = createIcon(P.Gear);
export const Settings2 = createIcon(P.GearSix);
export const Shield = createIcon(P.Shield);
export const ShieldAlert = createIcon(P.ShieldWarning);
export const ShieldCheck = createIcon(P.ShieldCheck);
export const SlidersHorizontal = createIcon(P.SlidersHorizontal);
export const Smartphone = createIcon(P.DeviceMobile);
export const Sparkles = createIcon(P.Sparkle);
export const Square = createIcon(P.Square);
export const Star = createIcon(P.Star);
export const Sun = createIcon(P.Sun);
export const Target = createIcon(P.Target);
export const Terminal = createIcon(P.TerminalWindow);
export const Timer = createIcon(P.Timer);
export const Trash = createIcon(P.Trash);
export const Trash2 = createIcon(P.TrashSimple);
export const TrendingUp = createIcon(P.TrendUp);
export const Trophy = createIcon(P.Trophy);
export const Unlock = createIcon(P.LockOpen);
export const Upload = createIcon(P.UploadSimple);
export const UploadCloud = createIcon(P.CloudArrowUp);
export const User = createIcon(P.User);
export const UserCircle = createIcon(P.UserCircle);
export const UserCog = createIcon(P.UserGear);
export const UserPlus = createIcon(P.UserPlus);
export const UserX = createIcon(P.UserMinus);
export const Users = createIcon(P.Users);
export const Users2 = createIcon(P.UsersThree);
export const Wand2 = createIcon(P.MagicWand);
export const Wifi = createIcon(P.WifiHigh);
export const WifiOff = createIcon(P.WifiSlash);
export const X = createIcon(P.X);
export const XCircle = createIcon(P.XCircle);
export const Zap = createIcon(P.Lightning);
export const ZoomIn = createIcon(P.MagnifyingGlassPlus);
export const ZoomOut = createIcon(P.MagnifyingGlassMinus);

// Re-export all other Phosphor icons so native Phosphor imports also work out of the box
export * from "@phosphor-icons/react";
